CXX = clang++
CXXFLAGS = -O2 -Wall -Wextra
INCLUDES = -I./include
LIBS = -L./lib/linux -l:libraylib.a -lm -lpthread -ldl -lGL -lX11 --std=c++23
TARGET = target/game

juego: src/main.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) src/main.cpp src/horse.cpp src/modes.cpp -o $(TARGET) $(LIBS)

clean:
	rm -f juego
